#!/bin/bash
export MKL_NUM_THREADS=$SLURM_CPUS_PER_TASK
srun python code/ground_state.py -path -thr 24 -mod FerHofSqu1 -chi 3000 -t1 1 -V 10 -Vtype Coulomb -Vrange 1 -n 12 77 -nphi 4 11 -LxMUC 1 -Ly 7
