#!/bin/bash

# supply command line arguments
# the batches that you want, in the order that you want e.g. ./run_piz 3 1 2

while test $# -gt 0
do
    case "$1" in
        1) sbatch scripts/run_phi_flow_piz &
           sbatch scripts/run_V_flow_piz &
           sbatch scripts/run_Ly_flow_piz &
           sbatch scripts/run_U_flow_piz &
            ;;
        2) sbatch scripts/run_phi_flow_piz2 &
           sbatch scripts/run_V_flow_piz2 &
           sbatch scripts/run_Ly_flow_piz2 &
           sbatch scripts/run_U_flow_piz2 &
            ;;
        3) sbatch scripts/run_phi_flow_piz3 &
           sbatch scripts/run_V_flow_piz3 &
           sbatch scripts/run_Ly_flow_piz3 &
           sbatch scripts/run_U_flow_piz3 &
            ;;
        *) echo "invalid argument $1"
            ;;
    esac
    shift
done
