#!/bin/bash

# supply command line arguments
# the batches that you want, in the order that you want e.g. ./run_hydra 3 1 2

while test $# -gt 0
do
    case "$1" in
        1) sbatch scripts/run_phi_flow_hydra &
           sbatch scripts/run_V_flow_hydra &
           sbatch scripts/run_Ly_flow_hydra &
            ;;
        2) sbatch scripts/run_phi_flow_hydra2 &
           sbatch scripts/run_V_flow_hydra2 &
           sbatch scripts/run_Ly_flow_hydra2 &
            ;;
        3) sbatch scripts/run_phi_flow_hydra3 &
           sbatch scripts/run_V_flow_hydra3 &
           sbatch scripts/run_Ly_flow_hydra3 &
            ;;
        *) echo "invalid argument $1"
            ;;
    esac
    shift
done