#!/bin/bash

SLOGS="/home/cluster/baandr/infinite_cylinder/slogs"
SJOBS_FILES="/home/cluster/baandr/infinite_cylinder/sjobs/final/*"

for FILE_PATH in $(ls $SJOBS_FILES | sort -t '_' -k11,11n -k9,9n)
do
	FILE="$(basename "$FILE_PATH")"  # strip the file from the path
	sbatch --output=$SLOGS/"$FILE".out --error=$SLOGS/"$FILE".err --job-name="$FILE" --mail-type=ALL \
	--mail-user=bandrews@physik.uzh.ch --qos=long --time=168:00:00 --mem=198G --ntasks=1 \
	--cpus-per-task=12 --threads-per-core=1 "$FILE_PATH"
done
