#!/bin/bash
#SBATCH --output=/home/cluster/baandr/infinite_cylinder/slogs/24_thread.out
#SBATCH --error=/home/cluster/baandr/infinite_cylinder/slogs/24_thread.err
#SBATCH --job-name=24_thread
#SBATCH --mail-type=ALL
#SBATCH --mail-user=bandrews@physik.uzh.ch
#SBATCH --qos=normal
#SBATCH --time=24:00:00
#SBATCH --mem=64G
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=24
#SBATCH --threads-per-core=1
###SBATCH --account=neupert.physik.uzh

# export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
export MKL_NUM_THREADS=$SLURM_CPUS_PER_TASK

srun python code/ground_state.py -path -thr 24 -mod FerHofSqu1 -chi 500 -t1 1 -V 10 -Vtype Coulomb -Vrange 1 -n 2 33 -nphi 2 11 -LxMUC 1 -Ly 6 -tag ".24_thread"
