#!/bin/bash
export MKL_NUM_THREADS=$SLURM_CPUS_PER_TASK
srun python code/ground_state.py -path -thr 12 -mod FerHofSqu1 -chi 1600 -t1 1 -V 10 -Vtype Coulomb -Vrange 1 -n 2 65 -nphi 5 13 -LxMUC 1 -Ly 7
