#!/bin/bash
export MKL_NUM_THREADS=$SLURM_CPUS_PER_TASK
srun python code/ground_state.py -path -thr 4 -mod FerHofSqu1 -chi 150 -t1 1 -V 10 -Vtype Coulomb -Vrange 1 -n 1 133 -nphi 5 19 -LxMUC 1 -Ly 14
