#!/bin/bash
export MKL_NUM_THREADS=$SLURM_CPUS_PER_TASK
srun python code/ground_state.py -path -thr 4 -mod FerHofSqu1 -chi 225 -t1 1 -V 10 -Vtype Coulomb -Vrange 1 -n 1 100 -nphi 7 20 -LxMUC 1 -Ly 10
