#!/bin/bash
export MKL_NUM_THREADS=$SLURM_CPUS_PER_TASK
srun python code/V_flow.py -path -thr 12 -mod FerHofSqu1 -chi 250 -t1 1 -Vtype Coulomb -Vrange 1 -n 2 9 -nphi 1 3 -LxMUC 1 -Ly 6 -V_min 0 -V_max 1 -V_samp 41
