#!/bin/bash
export MKL_NUM_THREADS=$SLURM_CPUS_PER_TASK
srun python code/ground_state.py -path -thr 4 -mod FerHofSqu1 -chi 200 -t1 1 -V 10 -Vtype Coulomb -Vrange 1 -n 2 105 -nphi 8 15 -LxMUC 1 -Ly 14
