#!/bin/bash
export MKL_NUM_THREADS=$SLURM_CPUS_PER_TASK
srun python code/phi_flow.py -path -thr 12 -mod FerHofSqu1 -chi 250 -t1 1 -V 10 -Vtype Coulomb -Vrange 1 -n 4 63 -nphi 1 7 -LxMUC 1 -Ly 9 -phi_min 0 -phi_max 9 -phi_samp 91
