#!/bin/bash
export MKL_NUM_THREADS=$SLURM_CPUS_PER_TASK
srun python code/V_flow.py -path -thr 12 -mod FerHofSqu1 -chi 25 -t1 1 -Vtype Coulomb -Vrange 1 -n 1 133 -nphi 5 19 -LxMUC 1 -Ly 14 -V_min 0 -V_max 1 -V_samp 41
