#!/bin/bash
#SBATCH --output=logs/Ly_flow_hydra.out
#SBATCH --error=logs/Ly_flow_hydra.err
#SBATCH --job-name=Ly_flow_hydra
#SBATCH --mail-type=ALL
#SBATCH --mail-user=bandrews@physik.uzh.ch
#SBATCH --time=01:00:00 
#SBATCH --mem=64G
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --ntasks-per-socket=6

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
export MKL_NUM_THREADS=$SLURM_CPUS_PER_TASK

srun python /home/cluster/baandr/infinite_cylinder/code/Ly_flow.py hydra
