#!/bin/bash
export MKL_NUM_THREADS=$SLURM_CPUS_PER_TASK
srun python code/phi_flow.py -path -thr 12 -mod FerHofSqu1 -chi 100 -t1 1 -V 10 -Vtype Coulomb -Vrange 1 -n 3 35 -nphi 1 5 -LxMUC 1 -Ly 14 -phi_min 0 -phi_max 7 -phi_samp 71
