#!/bin/bash
export MKL_NUM_THREADS=$SLURM_CPUS_PER_TASK
srun python code/phi_flow.py -path -thr 12 -mod FerHofSqu1 -chi 25 -t1 1 -V 10 -Vtype Coulomb -Vrange 1 -n 2 741 -nphi 8 39 -LxMUC 1 -Ly 19 -phi_min 0 -phi_max 19 -phi_samp 191
