#!/bin/bash
export MKL_NUM_THREADS=$SLURM_CPUS_PER_TASK
srun python code/ground_state.py -path -thr 24 -mod FerHofSqu1 -chi 2950 -t1 1 -V 10 -Vtype Coulomb -Vrange 1 -n 18 133 -nphi 6 19 -LxMUC 1 -Ly 7
